### ISSUE TITLE
Don't support for 3080 or 3090 GPU

### ISSUE THREAD

**Issue by tungbui198** [gungui98/deformable#1]
Same  issuse: https://github.com/CharlesShang/DCNv2/issues/88

Summary error:  nvcc fatal   : Unsupported gpu architecture 'compute_86'

Full log error: 
```
running install
running bdist_egg
running egg_info
creating deformConv.egg-info
writing deformConv.egg-info/PKG-INFO
writing dependency_links to deformConv.egg-info/dependency_links.txt
writing requirements to deformConv.egg-info/requires.txt
writing top-level names to deformConv.egg-info/top_level.txt
writing manifest file 'deformConv.egg-info/SOURCES.txt'
reading manifest file 'deformConv.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'deformConv.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.8
creating build/lib.linux-x86_64-3.8/deform_conv
copying deform_conv/__init__.py -> build/lib.linux-x86_64-3.8/deform_conv
creating build/lib.linux-x86_64-3.8/deform_conv/ops
copying deform_conv/ops/deform_conv.py -> build/lib.linux-x86_64-3.8/deform_conv/ops
copying deform_conv/ops/registry.py -> build/lib.linux-x86_64-3.8/deform_conv/ops
copying deform_conv/ops/__init__.py -> build/lib.linux-x86_64-3.8/deform_conv/ops
copying deform_conv/ops/deform_roi_pool.py -> build/lib.linux-x86_64-3.8/deform_conv/ops
creating build/lib.linux-x86_64-3.8/deform_conv/utils
copying deform_conv/utils/misc.py -> build/lib.linux-x86_64-3.8/deform_conv/utils
copying deform_conv/utils/ext_loader.py -> build/lib.linux-x86_64-3.8/deform_conv/utils
copying deform_conv/utils/registry.py -> build/lib.linux-x86_64-3.8/deform_conv/utils
copying deform_conv/utils/logging.py -> build/lib.linux-x86_64-3.8/deform_conv/utils
copying deform_conv/utils/__init__.py -> build/lib.linux-x86_64-3.8/deform_conv/utils
creating build/lib.linux-x86_64-3.8/deform_conv/ops/csrc
copying deform_conv/ops/csrc/common_cuda_helper.hpp -> build/lib.linux-x86_64-3.8/deform_conv/ops/csrc
copying deform_conv/ops/csrc/deform_conv_cuda_kernel.cuh -> build/lib.linux-x86_64-3.8/deform_conv/ops/csrc
copying deform_conv/ops/csrc/deform_roi_pool_cuda_kernel.cuh -> build/lib.linux-x86_64-3.8/deform_conv/ops/csrc
copying deform_conv/ops/csrc/modulated_deform_conv_cuda_kernel.cuh -> build/lib.linux-x86_64-3.8/deform_conv/ops/csrc
copying deform_conv/ops/csrc/pytorch_cpp_helper.hpp -> build/lib.linux-x86_64-3.8/deform_conv/ops/csrc
copying deform_conv/ops/csrc/pytorch_cuda_helper.hpp -> build/lib.linux-x86_64-3.8/deform_conv/ops/csrc
creating build/lib.linux-x86_64-3.8/deform_conv/ops/csrc/pytorch
copying deform_conv/ops/csrc/pytorch/deform_conv.cpp -> build/lib.linux-x86_64-3.8/deform_conv/ops/csrc/pytorch
copying deform_conv/ops/csrc/pytorch/deform_conv_cuda.cu -> build/lib.linux-x86_64-3.8/deform_conv/ops/csrc/pytorch
copying deform_conv/ops/csrc/pytorch/deform_roi_pool.cpp -> build/lib.linux-x86_64-3.8/deform_conv/ops/csrc/pytorch
copying deform_conv/ops/csrc/pytorch/deform_roi_pool_cuda.cu -> build/lib.linux-x86_64-3.8/deform_conv/ops/csrc/pytorch
copying deform_conv/ops/csrc/pytorch/info.cpp -> build/lib.linux-x86_64-3.8/deform_conv/ops/csrc/pytorch
copying deform_conv/ops/csrc/pytorch/modulated_deform_conv.cpp -> build/lib.linux-x86_64-3.8/deform_conv/ops/csrc/pytorch
copying deform_conv/ops/csrc/pytorch/modulated_deform_conv_cuda.cu -> build/lib.linux-x86_64-3.8/deform_conv/ops/csrc/pytorch
copying deform_conv/ops/csrc/pytorch/pybind.cpp -> build/lib.linux-x86_64-3.8/deform_conv/ops/csrc/pytorch
running build_ext
building 'deform_conv._ext' extension
creating /mnt/sdc/MOTF-project/deformable/build/temp.linux-x86_64-3.8
creating /mnt/sdc/MOTF-project/deformable/build/temp.linux-x86_64-3.8/deform_conv
creating /mnt/sdc/MOTF-project/deformable/build/temp.linux-x86_64-3.8/deform_conv/ops
creating /mnt/sdc/MOTF-project/deformable/build/temp.linux-x86_64-3.8/deform_conv/ops/csrc
creating /mnt/sdc/MOTF-project/deformable/build/temp.linux-x86_64-3.8/deform_conv/ops/csrc/pytorch
Emitting ninja build file /mnt/sdc/MOTF-project/deformable/build/temp.linux-x86_64-3.8/build.ninja...
Compiling objects...
Using envvar MAX_JOBS (4) as the number of workers...
[1/8] /usr/bin/nvcc  -DMMCV_WITH_CUDA -I/mnt/sdc/MOTF-project/deformable/deform_conv/ops/csrc -I/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include -I/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/TH -I/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/THC -I/home/bui.tien.tung/miniconda3/envs/py38_env/include/python3.8 -c -c /mnt/sdc/MOTF-project/deformable/deform_conv/ops/csrc/pytorch/modulated_deform_conv_cuda.cu -o /mnt/sdc/MOTF-project/deformable/build/temp.linux-x86_64-3.8/deform_conv/ops/csrc/pytorch/modulated_deform_conv_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
FAILED: /mnt/sdc/MOTF-project/deformable/build/temp.linux-x86_64-3.8/deform_conv/ops/csrc/pytorch/modulated_deform_conv_cuda.o 
/usr/bin/nvcc  -DMMCV_WITH_CUDA -I/mnt/sdc/MOTF-project/deformable/deform_conv/ops/csrc -I/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include -I/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/TH -I/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/THC -I/home/bui.tien.tung/miniconda3/envs/py38_env/include/python3.8 -c -c /mnt/sdc/MOTF-project/deformable/deform_conv/ops/csrc/pytorch/modulated_deform_conv_cuda.cu -o /mnt/sdc/MOTF-project/deformable/build/temp.linux-x86_64-3.8/deform_conv/ops/csrc/pytorch/modulated_deform_conv_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
nvcc fatal   : Unsupported gpu architecture 'compute_86'
[2/8] c++ -MMD -MF /mnt/sdc/MOTF-project/deformable/build/temp.linux-x86_64-3.8/deform_conv/ops/csrc/pytorch/info.o.d -pthread -B /home/bui.tien.tung/miniconda3/envs/py38_env/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMMCV_WITH_CUDA -I/mnt/sdc/MOTF-project/deformable/deform_conv/ops/csrc -I/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include -I/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/TH -I/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/THC -I/home/bui.tien.tung/miniconda3/envs/py38_env/include/python3.8 -c -c /mnt/sdc/MOTF-project/deformable/deform_conv/ops/csrc/pytorch/info.cpp -o /mnt/sdc/MOTF-project/deformable/build/temp.linux-x86_64-3.8/deform_conv/ops/csrc/pytorch/info.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/ATen/Parallel.h:140:0,
                 from /home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                 from /home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                 from /home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                 from /home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:13,
                 from /home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                 from /mnt/sdc/MOTF-project/deformable/deform_conv/ops/csrc/pytorch_cpp_helper.hpp:3,
                 from /mnt/sdc/MOTF-project/deformable/deform_conv/ops/csrc/pytorch/info.cpp:3:
/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/ATen/ParallelOpenMP.h:87:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
 #pragma omp parallel for if ((end - begin) >= grain_size)
 
[3/8] c++ -MMD -MF /mnt/sdc/MOTF-project/deformable/build/temp.linux-x86_64-3.8/deform_conv/ops/csrc/pytorch/deform_roi_pool.o.d -pthread -B /home/bui.tien.tung/miniconda3/envs/py38_env/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMMCV_WITH_CUDA -I/mnt/sdc/MOTF-project/deformable/deform_conv/ops/csrc -I/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include -I/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/TH -I/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/THC -I/home/bui.tien.tung/miniconda3/envs/py38_env/include/python3.8 -c -c /mnt/sdc/MOTF-project/deformable/deform_conv/ops/csrc/pytorch/deform_roi_pool.cpp -o /mnt/sdc/MOTF-project/deformable/build/temp.linux-x86_64-3.8/deform_conv/ops/csrc/pytorch/deform_roi_pool.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/ATen/Parallel.h:140:0,
                 from /home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                 from /home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                 from /home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                 from /home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:13,
                 from /home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                 from /mnt/sdc/MOTF-project/deformable/deform_conv/ops/csrc/pytorch_cpp_helper.hpp:3,
                 from /mnt/sdc/MOTF-project/deformable/deform_conv/ops/csrc/pytorch/deform_roi_pool.cpp:1:
/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/ATen/ParallelOpenMP.h:87:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
 #pragma omp parallel for if ((end - begin) >= grain_size)
 
[4/8] c++ -MMD -MF /mnt/sdc/MOTF-project/deformable/build/temp.linux-x86_64-3.8/deform_conv/ops/csrc/pytorch/deform_conv.o.d -pthread -B /home/bui.tien.tung/miniconda3/envs/py38_env/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMMCV_WITH_CUDA -I/mnt/sdc/MOTF-project/deformable/deform_conv/ops/csrc -I/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include -I/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/TH -I/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/THC -I/home/bui.tien.tung/miniconda3/envs/py38_env/include/python3.8 -c -c /mnt/sdc/MOTF-project/deformable/deform_conv/ops/csrc/pytorch/deform_conv.cpp -o /mnt/sdc/MOTF-project/deformable/build/temp.linux-x86_64-3.8/deform_conv/ops/csrc/pytorch/deform_conv.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/ATen/Parallel.h:140:0,
                 from /home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                 from /home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                 from /home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                 from /home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:13,
                 from /home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                 from /mnt/sdc/MOTF-project/deformable/deform_conv/ops/csrc/pytorch_cpp_helper.hpp:3,
                 from /mnt/sdc/MOTF-project/deformable/deform_conv/ops/csrc/pytorch/deform_conv.cpp:1:
/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/include/ATen/ParallelOpenMP.h:87:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
 #pragma omp parallel for if ((end - begin) >= grain_size)
 
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1666, in _run_ninja_build
    subprocess.run(
  File "/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '4']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 156, in <module>
    setup(
  File "/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 709, in build_extensions
    build_ext.build_extensions(self)
  File "/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 530, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1355, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/bui.tien.tung/miniconda3/envs/py38_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1682, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

**Comment by CaoHoangTung** [comment]
This may help you
https://github.com/CharlesShang/DCNv2/issues/88#issuecomment-1005358220
